version: "3"

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: mssql
    restart: always
    hostname: mssql
    environment:
      SA_PASSWORD: 123ASDqwe
      ACCEPT_EULA: Y
    volumes:
      - mssql:/var/opt/mssql/data
      - ./bk:/var/opt/mssql/backup
    ports:
      - "1433:1433"

volumes:
    mssql:

# Check file backup
# /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '123ASDqwe'-Q "RESTORE FILELISTONLY FROM DISK = '/var/opt/mssql/backup/xtlab.bak'"
# Store
# /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Password123' -Q 'RESTORE DATABASE xtlab FROM DISK = "/var/opt/mssql/backup/xtlab.bak" WITH MOVE "xtlab" TO "/var/opt/mssql/data/xtlab.mdf", MOVE "xtlab_log" TO "/var/opt/mssql/data/xtlab_log.ldf"'
# /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '123ASDqwe' -Q 'RESTORE DATABASE WorkAnalysis FROM DISK = "/var/opt/mssql/backup/xtlab.bak" WITH MOVE "xtlab" TO "/var/opt/mssql/data/xtlab.mdf", MOVE "xtlab_log" TO "/var/opt/mssql/data/xtlab_log.ldf"'